import { RegexPreset } from "./types";

export const LOG_PRESETS: RegexPreset[] = [
  // 1. Log Levels
  {
    id: "level-error-fatal",
    label: "Error & Fatal",
    category: "levels",
    pattern: "\\b(FATAL|CRITICAL|ERROR|SEVERE)\\b",
    description: "Match all critical, fatal, and error messages",
    example: "2026-09-22 [ERROR] Database connection lost",
    isRegex: true,
  },
  {
    id: "level-warn-error",
    label: "Warning & Error",
    category: "levels",
    pattern: "\\b(WARN(ING)?|ERR(OR)?|FATAL)\\b",
    description: "Match warnings, errors, and fatal failures",
    example: "2026-09-22 [WARN] High memory usage detected",
    isRegex: true,
  },
  {
    id: "level-info",
    label: "Info",
    category: "levels",
    pattern: "\\bINFO\\b",
    description: "Match informational runtime events",
    example: "2026-09-22 [INFO] Server started on port 3000",
    isRegex: true,
  },
  {
    id: "level-debug-trace",
    label: "Debug & Trace",
    category: "levels",
    pattern: "\\b(DEBUG|TRACE)\\b",
    description: "Match debug diagnostic and trace outputs",
    example: "2026-09-22 [DEBUG] Query execution took 12ms",
    isRegex: true,
  },

  // 2. Exceptions & Stack Traces
  {
    id: "exception-header",
    label: "Exception Headers",
    category: "exceptions",
    pattern: "\\b[a-zA-Z0-9_.]*(?:Exception|Error|Panic|Fatal):\\s.*",
    description: "Match Java, Python, Go, Node.js exception lines",
    example: "java.lang.NullPointerException: Object reference not set",
    isRegex: true,
  },
  {
    id: "stack-trace-lines",
    label: "Stack Trace Lines",
    category: "exceptions",
    pattern: "^\\s*(?:at\\s+|File\\s+\")[a-zA-Z0-9_./\\\\-]+",
    description: "Match stack trace frames (at ... / File '...')",
    example: "    at com.example.service.UserService.find(UserService.java:88)",
    isRegex: true,
  },
  {
    id: "caused-by",
    label: "Caused By",
    category: "exceptions",
    pattern: "^Caused by:\\s+.*",
    description: "Find root causes in nested Java/JVM exceptions",
    example: "Caused by: java.sql.SQLException: Connection refused",
    isRegex: true,
  },

  // 3. Timestamps
  {
    id: "iso-timestamp",
    label: "ISO-8601 Timestamp",
    category: "timestamps",
    pattern: "\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:?\\d{2})?",
    description: "Match standard ISO-8601 / RFC 3339 timestamps",
    example: "2026-09-22T14:02:11.458Z",
    isRegex: true,
  },
  {
    id: "standard-datetime",
    label: "Date Time (YYYY-MM-DD HH:mm:ss)",
    category: "timestamps",
    pattern: "\\b\\d{4}[-/]\\d{2}[-/]\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}\\b",
    description: "Match common standard date and time stamps",
    example: "2026-09-22 14:02:11",
    isRegex: true,
  },
  {
    id: "syslog-date",
    label: "Syslog / Apache Date",
    category: "timestamps",
    pattern: "\\b[A-Za-z]{3}\\s+\\d{1,2}\\s+\\d{2}:\\d{2}:\\d{2}\\b",
    description: "Match Syslog or Apache format dates",
    example: "Sep 22 14:02:11 myhost systemd[1]: Started service",
    isRegex: true,
  },

  // 4. HTTP & Network
  {
    id: "http-5xx",
    label: "HTTP 5xx (Server Error)",
    category: "http",
    pattern: "\\b5\\d{2}\\b",
    description: "Match HTTP 500, 502, 503, 504 server error status codes",
    example: 'POST /api/checkout HTTP/1.1" 500 241',
    isRegex: true,
  },
  {
    id: "http-4xx",
    label: "HTTP 4xx (Client Error)",
    category: "http",
    pattern: "\\b4\\d{2}\\b",
    description: "Match HTTP 400, 401, 403, 404 client error codes",
    example: 'GET /api/v1/user/99 HTTP/1.1" 404 120',
    isRegex: true,
  },
  {
    id: "http-requests",
    label: "HTTP Request Methods",
    category: "http",
    pattern: "\\b(GET|POST|PUT|DELETE|PATCH|OPTIONS|HEAD)\\s+\\S+",
    description: "Match HTTP verbs and request URL paths",
    example: "POST /v1/auth/login?redirect=dashboard",
    isRegex: true,
  },
  {
    id: "ipv4-address",
    label: "IPv4 Address",
    category: "network",
    pattern: "\\b(?:(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.){3}(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\b",
    description: "Match valid IPv4 addresses",
    example: "192.168.1.105 connected from 10.0.0.1",
    isRegex: true,
  },
  {
    id: "ipv4-port",
    label: "IPv4 Address with Port",
    category: "network",
    pattern: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}:\\d{2,5}\\b",
    description: "Match IP address with port notation",
    example: "Upstream server 10.244.0.15:8080 timed out",
    isRegex: true,
  },

  // 5. Identifiers
  {
    id: "uuid-trace-id",
    label: "UUID / Trace ID",
    category: "structured",
    pattern: "\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\b",
    description: "Match standard 36-character UUIDv4 / Correlation IDs",
    example: "trace_id=f47ac10b-58cc-4372-a567-0e02b2c3d479",
    isRegex: true,
  },
  {
    id: "hex-trace-id",
    label: "Hex Span / Trace ID (16/32 char)",
    category: "structured",
    pattern: "\\b[0-9a-fA-F]{16,32}\\b",
    description: "Match W3C OpenTelemetry or Jaeger trace IDs",
    example: "trace_id=4bf92f3577b34da6a3ce929d0e0e4736",
    isRegex: true,
  },

  // 6. Structured & Noise
  {
    id: "key-value",
    label: "Key-Value Pairs (k=v)",
    category: "structured",
    pattern: "\\b[a-zA-Z0-9_-]+=(?:\"[^\"]*\"|\\S+)",
    description: "Extract key=value parameters from structured logs",
    example: 'user_id=123 status="failed" duration_ms=45',
    isRegex: true,
  },
  {
    id: "json-error-log",
    label: "JSON Log with Error Level",
    category: "structured",
    pattern: '\\{.*"(?:level|severity)"\\s*:\\s*"(?:error|fatal)".*\\}',
    description: "Match JSON structured logs where level is error or fatal",
    example: '{"time":"2026-09-22","level":"error","msg":"disk full"}',
    isRegex: true,
  },
  {
    id: "exclude-health-checks",
    label: "Filter Out Health Checks (Invert)",
    category: "structured",
    pattern: "\\b(healthz|actuator\\/health|keep-alive|ping|readyz)\\b",
    description: "Exclude noisy probe lines (use with Invert Match)",
    example: "GET /healthz HTTP/1.1 200 OK",
    isRegex: true,
    invertMatch: true,
  },
];
